from .start import router as start_router
from .profile import router as profile_router
from .panel import router as panel_router
from .edit_profile import router as my_profile_router
from .look_profiles import router as look_profiles_router
from .look_who_likes_me import router as who_likes_me_router
from .keywords_psw import router as keywords_router
from .rating import router as rating_router
from .vip_user import router as vip_router
